sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: woaimama1748

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t8xtWtzxwHYLXAv6i7w
    access-key-secret:
    bucket-name: sky-take-out-wuyuan

  redis:
    host: localhost
    port: 6379
    password: woaimama1748
    database: 10